export const POKEMON_TYPES = [
  { value: "bug", label: "Inseto" },
  { value: "dark", label: "Sombrio" },
  { value: "dragon", label: "Dragão" },
  { value: "electric", label: "Elétrico" },
  { value: "fighting", label: "Lutador" },
  { value: "fire", label: "Fogo" },
  { value: "flying", label: "Voador" },
  { value: "ghost", label: "Fantasma" },
  { value: "grass", label: "Planta" },
  { value: "ground", label: "Terrestre" },
  { value: "ice", label: "Gelo" },
  { value: "normal", label: "Normal" },
  { value: "poison", label: "Venenoso" },
  { value: "psychic", label: "Psíquico" },
  { value: "rock", label: "Pedra" },
  { value: "steel", label: "Metálico" },
  { value: "water", label: "Água" },
];
